# Porta do server (Config Server + Eureka Server)
server.port=8888
spring.application.name=server

eureka.client.service-url.defaultZone=http://localhost:8888/eureka/

# Repositorio git com as configuracoes dos clientes (service-one.properties, service-two.properties, etc)
spring.cloud.config.server.git.uri=https://github.com/Fr44nc00/config-server.git

# Este Eureka não precisa se registrar nem buscar o registry dele mesmo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false