spring.application.name=main_microservice

server.port=8888

# Endereço do repositório git onde ficam os arquivos de configuração
spring.cloud.config.server.git.uri=git@github.com:Fr44nc00/config-server-aula.git

# Branch do repositório
spring.cloud.config.server.git.default-label=main

# Baixa as infos automaticamente do repositório
spring.cloud.config.server.git.clone-on-start=true

# Pasta dentro do repositório onde estão os arquivos de configuração
spring.cloud.config.server.git.search-paths=config

spring.cloud.config.import-check.enabled=false

# Não registre esse servidor no Eureka (já que ele é o próprio servidor)
eureka.client.register-with-eureka=false

# Não busca esse item na lista de serviços registrados
eureka.client.fetch-registry=false

# Nome do computador onde o Eureka está sendo executado
eureka.instance.hostname=localhost

# Desabilita o modo de proteção da Eureka (útil para testes e desenvolvimento)
eureka.server.enable-self-preservation=false