# Nome usado pra buscar config no Config Server e pra se registrar no Eureka
spring.application.name=service-one

server.port=8081

# Busca configuracao no Config Server (server, porta 8888)
spring.config.import=optional:configserver:http://localhost:8888

# Onde fica o Eureka Server pra este cliente se registrar
eureka.client.service-url.defaultZone=http://localhost:8888/eureka